baseURL = 'http://kushshukla24.github.io/'
languageCode = 'en-us'
title = 'Home | Kush Shukla'
author = 'Kush Shukla'
theme = ["raditian-free-hugo-theme", "lightbi-hugo"]

enableEmoji = true
enableRobotsTXT = true

[params.plugins]
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

[menu]
  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "/blog/"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Blog"
  URL = "/blog/"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]
  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager
  [params.logo]
    text1 = "Kush"
    text2 = "Shukla"
  [params.footer]
      copyright = "Â© Kush Shukla, 2023. All rights reserved."
